// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.0
// source: proto/replication/v1/replication.proto

package replicationpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AppendEntriesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       [][]byte               `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppendEntriesRequest) Reset() {
	*x = AppendEntriesRequest{}
	mi := &file_proto_replication_v1_replication_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppendEntriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendEntriesRequest) ProtoMessage() {}

func (x *AppendEntriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_replication_v1_replication_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendEntriesRequest.ProtoReflect.Descriptor instead.
func (*AppendEntriesRequest) Descriptor() ([]byte, []int) {
	return file_proto_replication_v1_replication_proto_rawDescGZIP(), []int{0}
}

func (x *AppendEntriesRequest) GetEntries() [][]byte {
	if x != nil {
		return x.Entries
	}
	return nil
}

type AppendEntriesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppendEntriesResponse) Reset() {
	*x = AppendEntriesResponse{}
	mi := &file_proto_replication_v1_replication_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppendEntriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendEntriesResponse) ProtoMessage() {}

func (x *AppendEntriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_replication_v1_replication_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendEntriesResponse.ProtoReflect.Descriptor instead.
func (*AppendEntriesResponse) Descriptor() ([]byte, []int) {
	return file_proto_replication_v1_replication_proto_rawDescGZIP(), []int{1}
}

func (x *AppendEntriesResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

var File_proto_replication_v1_replication_proto protoreflect.FileDescriptor

const file_proto_replication_v1_replication_proto_rawDesc = "" +
	"\n" +
	"&proto/replication/v1/replication.proto\x12\x0ereplication.v1\"0\n" +
	"\x14AppendEntriesRequest\x12\x18\n" +
	"\aentries\x18\x01 \x03(\fR\aentries\"3\n" +
	"\x15AppendEntriesResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted2k\n" +
	"\vReplication\x12\\\n" +
	"\rAppendEntries\x12$.replication.v1.AppendEntriesRequest\x1a%.replication.v1.AppendEntriesResponseBHZFgithub.com/NiranjanBhosale/logstore/internal/replication/replicationpbb\x06proto3"

var (
	file_proto_replication_v1_replication_proto_rawDescOnce sync.Once
	file_proto_replication_v1_replication_proto_rawDescData []byte
)

func file_proto_replication_v1_replication_proto_rawDescGZIP() []byte {
	file_proto_replication_v1_replication_proto_rawDescOnce.Do(func() {
		file_proto_replication_v1_replication_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_replication_v1_replication_proto_rawDesc), len(file_proto_replication_v1_replication_proto_rawDesc)))
	})
	return file_proto_replication_v1_replication_proto_rawDescData
}

var file_proto_replication_v1_replication_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_replication_v1_replication_proto_goTypes = []any{
	(*AppendEntriesRequest)(nil),  // 0: replication.v1.AppendEntriesRequest
	(*AppendEntriesResponse)(nil), // 1: replication.v1.AppendEntriesResponse
}
var file_proto_replication_v1_replication_proto_depIdxs = []int32{
	0, // 0: replication.v1.Replication.AppendEntries:input_type -> replication.v1.AppendEntriesRequest
	1, // 1: replication.v1.Replication.AppendEntries:output_type -> replication.v1.AppendEntriesResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_replication_v1_replication_proto_init() }
func file_proto_replication_v1_replication_proto_init() {
	if File_proto_replication_v1_replication_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_replication_v1_replication_proto_rawDesc), len(file_proto_replication_v1_replication_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_replication_v1_replication_proto_goTypes,
		DependencyIndexes: file_proto_replication_v1_replication_proto_depIdxs,
		MessageInfos:      file_proto_replication_v1_replication_proto_msgTypes,
	}.Build()
	File_proto_replication_v1_replication_proto = out.File
	file_proto_replication_v1_replication_proto_goTypes = nil
	file_proto_replication_v1_replication_proto_depIdxs = nil
}
